### ISSUE TITLE
Golang generator cannot find serverless.yaml

### ISSUE THREAD

**Issue by dieNachteule** [msolimans/generator-sls#10]
The serverless.yml file is expected to be at the root of the project. In the golang generator it is placed at ./serverless/serverless.yml. So, after he Unit Test Framework question:

Error: ENOENT: no such file or directory, open {my-path-to-source-root}/serverless.yml

**Comment by msolimans** [comment]
Sorry I had not looked at project for awhile, @powered-toast can you please post complete logs and history of commands and selected options you went through to be able to understand the nature of this issue.
